//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWCF.Contracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatType", Namespace="http://schemas.datacontract.org/2004/07/CoreWCF.Contracts")]
    public partial class CatType : object
    {
        
        private bool LikesChildrenField;
        
        private string RaceNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LikesChildren
        {
            get
            {
                return this.LikesChildrenField;
            }
            set
            {
                this.LikesChildrenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RaceName
        {
            get
            {
                return this.RaceNameField;
            }
            set
            {
                this.RaceNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatLoverFault", Namespace="http://schemas.datacontract.org/2004/07/CoreWCF.Contracts")]
    public partial class CatLoverFault : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private System.DateTime ErrorTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ErrorTimestamp
        {
            get
            {
                return this.ErrorTimestampField;
            }
            set
            {
                this.ErrorTimestampField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICatInformationService")]
public interface ICatInformationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatInformationService/GetPhoto", ReplyAction="http://tempuri.org/ICatInformationService/GetPhotoResponse")]
    System.Threading.Tasks.Task<GetPhotoResponse> GetPhotoAsync(GetPhotoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatInformationService/GetCatTypes", ReplyAction="http://tempuri.org/ICatInformationService/GetCatTypesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(CoreWCF.Contracts.CatLoverFault), Action="http://tempuri.org/ICatInformationService/GetCatTypesCatLoverFaultFault", Name="CatLoverFault", Namespace="http://schemas.datacontract.org/2004/07/CoreWCF.Contracts")]
    System.Threading.Tasks.Task<GetCatTypesResponse> GetCatTypesAsync(GetCatTypesRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetPhoto", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetPhotoRequest
{
    
    public GetPhotoRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetPhotoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetPhotoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public byte[] GetPhotoResult;
    
    public GetPhotoResponse()
    {
    }
    
    public GetPhotoResponse(byte[] GetPhotoResult)
    {
        this.GetPhotoResult = GetPhotoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCatTypesRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetCatTypesRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public string CatLoverHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public bool LikesChildren;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string RequestId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public System.DateTime RequestTimestamp;
    
    public GetCatTypesRequest()
    {
    }
    
    public GetCatTypesRequest(string CatLoverHeader, bool LikesChildren, string RequestId, System.DateTime RequestTimestamp)
    {
        this.CatLoverHeader = CatLoverHeader;
        this.LikesChildren = LikesChildren;
        this.RequestId = RequestId;
        this.RequestTimestamp = RequestTimestamp;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCatTypesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetCatTypesResponse
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public string ResponseId;
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public int TotalCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public CoreWCF.Contracts.CatType[] CatTypes;
    
    public GetCatTypesResponse()
    {
    }
    
    public GetCatTypesResponse(string ResponseId, int TotalCount, CoreWCF.Contracts.CatType[] CatTypes)
    {
        this.ResponseId = ResponseId;
        this.TotalCount = TotalCount;
        this.CatTypes = CatTypes;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface ICatInformationServiceChannel : ICatInformationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class CatInformationServiceClient : System.ServiceModel.ClientBase<ICatInformationService>, ICatInformationService
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public CatInformationServiceClient() : 
            base(CatInformationServiceClient.GetDefaultBinding(), CatInformationServiceClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICatInformationService.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CatInformationServiceClient(EndpointConfiguration endpointConfiguration) : 
            base(CatInformationServiceClient.GetBindingForEndpoint(endpointConfiguration), CatInformationServiceClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CatInformationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(CatInformationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CatInformationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(CatInformationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CatInformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<GetPhotoResponse> GetPhotoAsync(GetPhotoRequest request)
    {
        return base.Channel.GetPhotoAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetCatTypesResponse> GetCatTypesAsync(GetCatTypesRequest request)
    {
        return base.Channel.GetCatTypesAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICatInformationService))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICatInformationService))
        {
            return new System.ServiceModel.EndpointAddress("https://localhost:5002/CatInformationService");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return CatInformationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICatInformationService);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return CatInformationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICatInformationService);
    }
    
    public enum EndpointConfiguration
    {
        
        BasicHttpBinding_ICatInformationService,
    }
}
